#pragma once

#define ParamAPP_Number_Melodies 0
#define ParamAPP_Melody_1 ""
#define ParamAPP_Melody_2 ""
#define ParamAPP_Melody_3 ""
#define ParamAPP_Melody_4 ""
#define ParamAPP_Melody_5 ""
#define ParamAPP_Melody_6 ""
#define ParamAPP_Melody_7 ""
#define ParamAPP_Melody_8 ""
#define ParamAPP_Melody_1_Melody_Pause 0
#define ParamAPP_Melody_2_Melody_Pause 0
#define ParamAPP_Melody_3_Melody_Pause 0
#define ParamAPP_Melody_4_Melody_Pause 0
#define ParamAPP_Melody_5_Melody_Pause 0
#define ParamAPP_Melody_6_Melody_Pause 0
#define ParamAPP_Melody_7_Melody_Pause 0
#define ParamAPP_Melody_8_Melody_Pause 0
#define ParamAPP_Melody_1___Mode 0
#define ParamAPP_Melody_2___Mode 0
#define ParamAPP_Melody_3___Mode 0
#define ParamAPP_Melody_4___Mode 0
#define ParamAPP_Melody_5___Mode 0
#define ParamAPP_Melody_6___Mode 0
#define ParamAPP_Melody_7___Mode 0
#define ParamAPP_Melody_8___Mode 0
#define APP_KoTrigger_Melody_1 0
#define APP_KoTrigger_Melody_2 0
#define APP_KoTrigger_Melody_3 0
#define APP_KoTrigger_Melody_4 0
#define APP_KoTrigger_Melody_5 0
#define APP_KoTrigger_Melody_6 0
#define APP_KoTrigger_Melody_7 0
#define APP_KoTrigger_Melody_8 0
#define APP_KoSWITCH_Melody_1 0
#define APP_KoSWITCH_Melody_2 0
#define APP_KoSWITCH_Melody_3 0
#define APP_KoSWITCH_Melody_4 0
#define APP_KoSWITCH_Melody_5 0
#define APP_KoSWITCH_Melody_6 0
#define APP_KoSWITCH_Melody_7 0
#define APP_KoSWITCH_Melody_8 0
#define APP_KoTemperature_Melody_1 0
#define APP_KoTemperature_Melody_2 0
#define APP_KoTemperature_Melody_3 0
#define APP_KoTemperature_Melody_4 0
#define APP_KoTemperature_Melody_5 0
#define APP_KoTemperature_Melody_6 0
#define APP_KoTemperature_Melody_7 0
#define APP_KoTemperature_Melody_8 0
#define ParamAPP_Melody_1___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_2___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_3___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_4___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_5___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_6___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_7___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_8___Lower_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_1___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_2___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_3___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_4___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_5___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_6___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_7___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_8___Upper_Temp_Exclusion_Limit 0
#define ParamAPP_Melody_1___Duration 0
#define ParamAPP_Melody_2___Duration 0
#define ParamAPP_Melody_3___Duration 0
#define ParamAPP_Melody_4___Duration 0
#define ParamAPP_Melody_5___Duration 0
#define ParamAPP_Melody_6___Duration 0
#define ParamAPP_Melody_7___Duration 0
#define ParamAPP_Melody_8___Duration 0
#define MAIN_ApplicationVersion 0x10
